### ISSUE TITLE
Add header to the `/notes` page

### ISSUE THREAD

**Issue by MgenGlder** [dearborn-coding-club/website-base-frontend#38]
## Description
- Right now, on the `/notes` page (dearborncodingclub.com/notes), we don't have the sticky header. We can import this into other pages using the `NavBar.tsx` component.

![Image](https://github.com/user-attachments/assets/cfcb58f3-fb5b-4bb0-8e1d-03f9ec157136)

**Comment by Duke242** [comment]
References: https://github.com/dearborn-coding-club/website-base-frontend/pull/40
