### ISSUE TITLE
Pressing the 'DCC' logo in the top left corner should navigate the user to the homepage.

### ISSUE THREAD

**Issue by Duke242** [dearborn-coding-club/website-base-frontend#47]
Clicking the 'DCC' logo should redirect the user to the homepage of the application.

**Comment by MgenGlder** [comment]
This is a good idea, I'm with it 👍🏾 .

**Comment by Duke242** [comment]
Mostly for mobile screens when at the notes page. 

References: https://github.com/dearborn-coding-club/website-base-frontend/pull/48
