### ISSUE TITLE
Adjust the size of the slide-out menu

### ISSUE THREAD

**Issue by MgenGlder** [dearborn-coding-club/website-base-frontend#49]
## Description
Right now, the slide out from the hamburger menu takes up the entire page. To me, this looks excessive and disrupts the flow of the page. We should reduce the amount of screen overlay that the slide out menu takes up. A notable exception is that on mobile, it may be ok to make the slide out menu take up the entire screen. We can investigate this.

**Comment by Duke242** [comment]
References: https://github.com/dearborn-coding-club/website-base-frontend/pull/50
